### ISSUE TITLE
Minor Issues In Released Font

### ISSUE THREAD

**Issue by HieroUser** [microsoft/font-tools#42]
I would like to say first and foremost, this is a wonderful font which works excellently well and I'm greatly appreciative of the release of the font publicly. This is significantly better than most of the tools/fonts that have existed so far, however with many glyph combinations under many circumstances there are ratio distortions.

Notable examples Include (Without Spaces): 
𓂓 𓐰  𓇅
and 
𓏞 𓐰 𓂓

There are also circumstances of misalignment and ratio distortion when using the overlay feature and the corner feature respectively. The later in this case is minor yet noticeable.

Example:𓇅 𓐶 𓂓 and 𓅓 𓐴 𓎡

Also:𓅓 𓐴 𓎡 𓐴 𓅓  

Leads to a strange issue which will induce subscript.

Lastly, there is an issue which may take a while to fix but is completely fixable. in many glyph combinations the thickness outline of each glyph is mismatched which isn't aesthetically ideal.

I would like to thank the developer for pursuing this project, however, I do hope improvements and alternate fonts for example the one used in JSesh can be re-rendered using this tool to have format control functionality. Additionally, most people have no idea how to render the font using python and VOLT and keep running into various errors, if you want to improve the build instructions please make it a YouTube video going through the process step by step.

I hope over time an improved version of this font can be integrated into windows/most word processing/video processing applications and the web as a whole natively and as standard.

**Comment by xadxura** [comment]
Thank you, @HieroUser, for this excellent feedback! It is very much appreciated.

Generally speaking, there are four kinds of issues that relate to this font.

1. There are structural issues that concern the OpenType code. I will prioritize fixing these issues as they will impact any font that uses this code to generate the Hieroglyph clustering in OpenType.

2. There are font glyph issues that affect this font only. While I will make an effort to fix this type of issue, it is really outside of the scope of this project which intends to provide a reference font that supports the Egyptian Hieroglyph Format Controls characters. It is simply the case that perfecting the glyph outlines for thousands of glyphs takes more time than I have available.

3. Input errors. If the input sequence doesn't conform to expectations, the rendering may be suboptimal. Generally these expectations are defined in [The Unicode Standard](https://www.unicode.org/versions/Unicode15.0.0/ch11.pdf), or in the two proposals for the [U12](https://www.unicode.org/L2/L2017/17112r-quadrat-encoding.pdf) and [U15}(https://www.unicode.org/L2/L2021/21208-egyptian-ctrl.pdf) sets of format controls. But some issues remain to be documented fully.

4. Rendering system errors. Accurate rendering using this font depends on the rendering system used by an application, and it's level of support for Unicode and OpenType shaping.

Onto your feedback:

- Ratio distortion: D28 vj M13 𓂓 𓐰 𓇅
This is a type 2 issue. I've fixed this by removing some of the more distorted size variants of M13 from the seed font. This has the effect of improving the form of this block as far as M13 is concerned. I've not attempted to fix the rendering of D28.
![image](https://github.com/microsoft/font-tools/assets/8731579/55e5d5ae-6e5b-466a-895c-0a6caf14550a)
I've fixed the 

- Ratio distortion: Y3 vj D28 𓏞 𓐰 𓂓
This is a type 2 issue. I've not attempted to fix the ratio of D28. The outline of Y3 at this size is perhaps distorted. If that is the case, it can be fixed by removing the particular size variant. The Y3 variants need to be redrawn at each size to have a better weight at the small sizes. That's something that can be addressed over time. Ideally, I'll open the font glyphs to contributors.

- Misalignment: M13 + D28 𓇅 𓐶 𓂓
This is a type 3 issue. Due to ordering ambiguity for stacked forms, the font logic requires the wider form to be entered first. This has been discussed but has not yet been documented. When rendered D28 + M13, the form is more acceptable.
![image](https://github.com/microsoft/font-tools/assets/8731579/51ef27e5-6c42-46f3-abcd-9d62094beff6)

- Ratio distortion: G17 te V31  𓅓 𓐴 𓎡 
This is a type 2 issue. The best approach will be to fix the outline of V31 at the target size for this form. Another option would be to create a ligature glyph for this combination.

- Subscription: G17 te V31 te G17  𓅓 𓐴 𓎡 𓐴 𓅓
This is primarily a type 3 issue. The sequence is invalid because only one insertion can be applied to the same corner. The font logic could be extended to better guard against invalid sequences. This is something for a future update.

- Indeed, the glyph outlines for the many size variants require improvement. This is a type 2 issue that will take a long time to address completely.

Please keep the feedback coming!

@xadxura
